source funcs

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,8 +1,10 @@
-trap 'ret=$?; test $ret -ne 0 && printf "\n   \e[31m\033[0m  Shiny failed  \e[31m\033[0m\n" >&2; exit $ret' EXIT
+trap 'ret=$?; test $ret -ne 0 && printf "\n   \e[31m\033[0m  Bootstrap failed  \e[31m\033[0m\n" >&2; exit $ret' EXIT
 
 set -e
 
 ask_for_sudo
+
+source funcs
 
 if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
 	test -d "${xpath}" && test -x "${xpath}" ; then
@@ -16,8 +18,6 @@ fi
 if [ ! -d "$HOME/.bin/" ]; then
 	mkdir "$HOME/.bin"
 fi
-
-
 
 if ! [ -x "$(command -v brew)" ]; then
 	step "Installing Homebrew…"
@@ -37,15 +37,19 @@ fi
 if ! [ -x "$(command -v mas)" ]; then
 	step "Installing mas-cli…"
     brew install mas
-	print_success "Homebrew installed!"
+	print_success "mas-cli installed!"
+	step "Configuring mas-cli…"
+	read -p "Enter Apple ID:" appleid
+	mas signin --dialog $appleid
+	print_success "mas-cli configured!"
 else
-	print_success_muted "Homebrew already installed. Skipping."
+	print_success_muted "mas-cli already installed. Skipping."
 fi
 
 if [ -e Brewfile ]; then
     brew bundle
 else
-	printf "\n ⚠️  Brewfile not found, how are we suppoed to install things? 🤔 \n"
+	printf "\n ⚠️  Brewfile not found, how are we supposed to install things? 🤔 \n"
     exit 1
 fi
 
@@ -159,6 +163,13 @@ sudo chflags nohidden /Volumes
 
 # Automatically hide and show the Dock
 defaults write com.apple.dock autohide -bool true
+
+step "Setting Computer Name"
+read -p "Enter Computer Name:" hostname
+sudo scutil --set HostName $hostname
+sudo scutil --set LocalHostName $hostname
+sudo scutil --set ComputerName $hostname
+dscacheutil -flushcache
 
 print_success "Done configuring MacOS Settings"
 
